[package]
name = "plantarium"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.7.3", features = ["router"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "js"] }
chrono = { version = "0.4", features = ["serde"] }
gloo-storage = { version = "0.3", optional = true }
pulldown-cmark = "0.12"
ammonia = "4"
rusqlite = { version = "0.30", features = ["bundled"] }
directories = "5.0"

[features]
default = ["web"]
web = ["dioxus/web", "gloo-storage"]
desktop = ["dioxus/desktop"]

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
incremental = false
